package com.example.nutritiontracker.utils

import com.example.nutritiontracker.data.datasource.local.entities.MealEntity
import com.example.nutritiontracker.data.datasource.remote.retrofitModels.Meal
import com.example.nutritiontracker.data.datasource.remote.retrofitModels.MealDetails
import com.example.nutritiontracker.data.datasource.remote.retrofitModels.PlanedMeal

class Mapper {


    companion object {

        fun mealToMealEntity(meal: MealDetails): MealEntity =
            MealEntity(
                idMeal = safeStr(meal.idMeal),
                strArea = safeStr(meal.strArea),
                strCategory = safeStr(meal.strCategory),
                strIngredient1 = safeStr(meal.strIngredient1),
                strIngredient10 = safeStr(meal.strIngredient10),
                strIngredient11 = safeStr(meal.strIngredient11),
                strIngredient12 = safeStr(meal.strIngredient12),
                strIngredient13 = safeStr(meal.strIngredient13),
                strIngredient14 = safeStr(meal.strIngredient14),
                strIngredient15 = safeStr(meal.strIngredient15),
                strIngredient16 = safeStr(meal.strIngredient16),
                strIngredient17 = safeStr(meal.strIngredient17),
                strIngredient18 = safeStr(meal.strIngredient18),
                strIngredient19 = safeStr(meal.strIngredient19),
                strIngredient2 = safeStr(meal.strIngredient2),
                strIngredient20 = safeStr(meal.strIngredient20),
                strIngredient4 = safeStr(meal.strIngredient4),
                strIngredient5 = safeStr(meal.strIngredient5),
                strIngredient6 = safeStr(meal.strIngredient6),
                strIngredient7 = safeStr(meal.strIngredient7),
                strIngredient8 = safeStr(meal.strIngredient8),
                strIngredient9 = safeStr(meal.strIngredient9),
                strInstructions = safeStr(meal.strInstructions),
                strMeal = safeStr(meal.strMeal),
                strMealThumb = safeStr(meal.strMealThumb),
                strMeasure1 = safeStr(meal.strMeasure1),
                strMeasure10 = safeStr(meal.strMeasure10),
                strMeasure11 = safeStr(meal.strMeasure11),
                strMeasure12 = safeStr(meal.strMeasure12),
                strMeasure13 = safeStr(meal.strMeasure13),
                strMeasure14 = safeStr(meal.strMeasure14),
                strMeasure15 = safeStr(meal.strMeasure15),
                strMeasure16 = safeStr(meal.strMeasure16),
                strMeasure17 = safeStr(meal.strMeasure17),
                strMeasure18 = safeStr(meal.strMeasure18),
                strMeasure19 = safeStr(meal.strMeasure19),
                strMeasure2 = safeStr(meal.strMeasure2),
                strMeasure20 = safeStr(meal.strMeasure20),
                strMeasure3 = safeStr(meal.strMeasure3),
                strMeasure4 = safeStr(meal.strMeasure4),
                strMeasure5 = safeStr(meal.strMeasure5),
                strMeasure6 = safeStr(meal.strMeasure6),
                strMeasure7 = safeStr(meal.strMeasure7),
                strMeasure8 = safeStr(meal.strMeasure8),
                strMeasure9 = safeStr(meal.strMeasure9),
                strTags = safeStr(meal.strTags),
                strYoutube = safeStr(meal.strYoutube)
            )

        fun mealEntityToMealDetails(meal: MealEntity): MealDetails =
            MealDetails(
                idMeal = safeStr(meal.idMeal),
                strArea = safeStr(meal.strArea),
                strCategory = safeStr(meal.strCategory),
                strIngredient1 = safeStr(meal.strIngredient1),
                strIngredient10 = safeStr(meal.strIngredient10),
                strIngredient11 = safeStr(meal.strIngredient11),
                strIngredient12 = safeStr(meal.strIngredient12),
                strIngredient13 = safeStr(meal.strIngredient13),
                strIngredient14 = safeStr(meal.strIngredient14),
                strIngredient15 = safeStr(meal.strIngredient15),
                strIngredient16 = safeStr(meal.strIngredient16),
                strIngredient17 = safeStr(meal.strIngredient17),
                strIngredient18 = safeStr(meal.strIngredient18),
                strIngredient19 = safeStr(meal.strIngredient19),
                strIngredient2 = safeStr(meal.strIngredient2),
                strIngredient20 = safeStr(meal.strIngredient20),
                strIngredient4 = safeStr(meal.strIngredient4),
                strIngredient5 = safeStr(meal.strIngredient5),
                strIngredient6 = safeStr(meal.strIngredient6),
                strIngredient7 = safeStr(meal.strIngredient7),
                strIngredient8 = safeStr(meal.strIngredient8),
                strIngredient9 = safeStr(meal.strIngredient9),
                strInstructions = safeStr(meal.strInstructions),
                strMeal = safeStr(meal.strMeal),
                strMealThumb = safeStr(meal.strMealThumb),
                strMeasure1 = safeStr(meal.strMeasure1),
                strMeasure10 = safeStr(meal.strMeasure10),
                strMeasure11 = safeStr(meal.strMeasure11),
                strMeasure12 = safeStr(meal.strMeasure12),
                strMeasure13 = safeStr(meal.strMeasure13),
                strMeasure14 = safeStr(meal.strMeasure14),
                strMeasure15 = safeStr(meal.strMeasure15),
                strMeasure16 = safeStr(meal.strMeasure16),
                strMeasure17 = safeStr(meal.strMeasure17),
                strMeasure18 = safeStr(meal.strMeasure18),
                strMeasure19 = safeStr(meal.strMeasure19),
                strMeasure2 = safeStr(meal.strMeasure2),
                strMeasure20 = safeStr(meal.strMeasure20),
                strMeasure3 = safeStr(meal.strMeasure3),
                strMeasure4 = safeStr(meal.strMeasure4),
                strMeasure5 = safeStr(meal.strMeasure5),
                strMeasure6 = safeStr(meal.strMeasure6),
                strMeasure7 = safeStr(meal.strMeasure7),
                strMeasure8 = safeStr(meal.strMeasure8),
                strMeasure9 = safeStr(meal.strMeasure9),
                strTags = safeStr(meal.strTags),
                strYoutube = safeStr(meal.strYoutube)
            )

        fun mealEntityToMeal(mealEntity: MealEntity): Meal =
            Meal(
                idMeal = safeStr(mealEntity.idMeal),
                strMeal = safeStr(mealEntity.strMeal),
                strMealThumb = safeStr(mealEntity.strMealThumb)
            )

        fun mealDetailsToPlanedMeal(meal: MealDetails): PlanedMeal =
            PlanedMeal(
                id = meal.id,
                dateToEat = meal.dateToEat,
                mealType = meal.mealType,
                saved = true,

                idMeal = safeStr(meal.idMeal),
                strArea = safeStr(meal.strArea),
                strCategory = safeStr(meal.strCategory),
                strIngredient1 = safeStr(meal.strIngredient1),
                strIngredient10 = safeStr(meal.strIngredient10),
                strIngredient11 = safeStr(meal.strIngredient11),
                strIngredient12 = safeStr(meal.strIngredient12),
                strIngredient13 = safeStr(meal.strIngredient13),
                strIngredient14 = safeStr(meal.strIngredient14),
                strIngredient15 = safeStr(meal.strIngredient15),
                strIngredient16 = safeStr(meal.strIngredient16),
                strIngredient17 = safeStr(meal.strIngredient17),
                strIngredient18 = safeStr(meal.strIngredient18),
                strIngredient19 = safeStr(meal.strIngredient19),
                strIngredient2 = safeStr(meal.strIngredient2),
                strIngredient20 = safeStr(meal.strIngredient20),
                strIngredient3 = safeStr(meal.strIngredient3),
                strIngredient4 = safeStr(meal.strIngredient4),
                strIngredient5 = safeStr(meal.strIngredient5),
                strIngredient6 = safeStr(meal.strIngredient6),
                strIngredient7 = safeStr(meal.strIngredient7),
                strIngredient8 = safeStr(meal.strIngredient8),
                strIngredient9 = safeStr(meal.strIngredient9),
                strInstructions = safeStr(meal.strInstructions),
                strMeal = safeStr(meal.strMeal),
                strMealThumb = safeStr(meal.strMealThumb),
                strMeasure1 = safeStr(meal.strMeasure1),
                strMeasure10 = safeStr(meal.strMeasure10),
                strMeasure11 = safeStr(meal.strMeasure11),
                strMeasure12 = safeStr(meal.strMeasure12),
                strMeasure13 = safeStr(meal.strMeasure13),
                strMeasure14 = safeStr(meal.strMeasure14),
                strMeasure15 = safeStr(meal.strMeasure15),
                strMeasure16 = safeStr(meal.strMeasure16),
                strMeasure17 = safeStr(meal.strMeasure17),
                strMeasure18 = safeStr(meal.strMeasure18),
                strMeasure19 = safeStr(meal.strMeasure19),
                strMeasure2 = safeStr(meal.strMeasure2),
                strMeasure20 = safeStr(meal.strMeasure20),
                strMeasure3 = safeStr(meal.strMeasure3),
                strMeasure4 = safeStr(meal.strMeasure4),
                strMeasure5 = safeStr(meal.strMeasure5),
                strMeasure6 = safeStr(meal.strMeasure6),
                strMeasure7 = safeStr(meal.strMeasure7),
                strMeasure8 = safeStr(meal.strMeasure8),
                strMeasure9 = safeStr(meal.strMeasure9),
                strTags = safeStr(meal.strTags),
                strYoutube = safeStr(meal.strYoutube),

                dateModified = "",
                strCreativeCommonsConfirmed = "",
                strDrinkAlternate = "",
                strImageSource = "",
                strSource = ""
            )

        fun mealEntityToPlanedMeal(mealEntity: MealEntity): PlanedMeal =
            PlanedMeal(
                id = mealEntity.id,
                dateToEat = mealEntity.dateToEat,
                mealType = mealEntity.mealType,
                saved = true,

                idMeal = safeStr(mealEntity.idMeal),
                strArea = safeStr(mealEntity.strArea),
                strCategory = safeStr(mealEntity.strCategory),
                strIngredient1 = safeStr(mealEntity.strIngredient1),
                strIngredient10 = safeStr(mealEntity.strIngredient10),
                strIngredient11 = safeStr(mealEntity.strIngredient11),
                strIngredient12 = safeStr(mealEntity.strIngredient12),
                strIngredient13 = safeStr(mealEntity.strIngredient13),
                strIngredient14 = safeStr(mealEntity.strIngredient14),
                strIngredient15 = safeStr(mealEntity.strIngredient15),
                strIngredient16 = safeStr(mealEntity.strIngredient16),
                strIngredient17 = safeStr(mealEntity.strIngredient17),
                strIngredient18 = safeStr(mealEntity.strIngredient18),
                strIngredient19 = safeStr(mealEntity.strIngredient19),
                strIngredient2 = safeStr(mealEntity.strIngredient2),
                strIngredient20 = safeStr(mealEntity.strIngredient20),
                strIngredient3 = safeStr(mealEntity.strIngredient3),
                strIngredient4 = safeStr(mealEntity.strIngredient4),
                strIngredient5 = safeStr(mealEntity.strIngredient5),
                strIngredient6 = safeStr(mealEntity.strIngredient6),
                strIngredient7 = safeStr(mealEntity.strIngredient7),
                strIngredient8 = safeStr(mealEntity.strIngredient8),
                strIngredient9 = safeStr(mealEntity.strIngredient9),
                strInstructions = safeStr(mealEntity.strInstructions),
                strMeal = safeStr(mealEntity.strMeal),
                strMealThumb = safeStr(mealEntity.strMealThumb),
                strMeasure1 = safeStr(mealEntity.strMeasure1),
                strMeasure10 = safeStr(mealEntity.strMeasure10),
                strMeasure11 = safeStr(mealEntity.strMeasure11),
                strMeasure12 = safeStr(mealEntity.strMeasure12),
                strMeasure13 = safeStr(mealEntity.strMeasure13),
                strMeasure14 = safeStr(mealEntity.strMeasure14),
                strMeasure15 = safeStr(mealEntity.strMeasure15),
                strMeasure16 = safeStr(mealEntity.strMeasure16),
                strMeasure17 = safeStr(mealEntity.strMeasure17),
                strMeasure18 = safeStr(mealEntity.strMeasure18),
                strMeasure19 = safeStr(mealEntity.strMeasure19),
                strMeasure2 = safeStr(mealEntity.strMeasure2),
                strMeasure20 = safeStr(mealEntity.strMeasure20),
                strMeasure3 = safeStr(mealEntity.strMeasure3),
                strMeasure4 = safeStr(mealEntity.strMeasure4),
                strMeasure5 = safeStr(mealEntity.strMeasure5),
                strMeasure6 = safeStr(mealEntity.strMeasure6),
                strMeasure7 = safeStr(mealEntity.strMeasure7),
                strMeasure8 = safeStr(mealEntity.strMeasure8),
                strMeasure9 = safeStr(mealEntity.strMeasure9),
                strTags = safeStr(mealEntity.strTags),
                strYoutube = safeStr(mealEntity.strYoutube),

                dateModified = "",
                strCreativeCommonsConfirmed = "",
                strDrinkAlternate = "",
                strImageSource = "",
                strSource = ""
            )


        private fun safeStr(str: Any?): String = str?.toString() ?: ""
    }



}